spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/opgg;MODE=MYSQL
    url: jdbc:mysql://opgg.cql0y5x56ezx.ap-northeast-2.rds.amazonaws.com:3306/opgg
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:mysql://opgg.cql0y5x56ezx.ap-northeast-2.rds.amazonaws.com:3306/opgg

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        dialect.storage_engine: innodb
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace